---
title: "`r params$title`"
author: "riri"
date: "2023-09-19"
output: html_document
editor_options:
    chunk_output_type: inline
params:
  title: NULL
  wd: NULL
  assets: NULL
---

```{r load_libraries, cache = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(readr)
library(RColorBrewer)
library(ggplot2)
library(Seurat)
library(dittoSeq)
library(SCpubr)

# custom functions
setwd(params$wd)
```

```{r setup}

knitr::opts_chunk$set(
  # Display PNG in HTML file, but also keep PDF outputs in figures folder
  dev = c("png", "pdf"), 
  # Keep all the figures produced in a chunk
  fig.keep = "all",      
  # Save all figures to this output folder
  fig.path = file.path(params$wd,'figures/'),
  # Do not cache results
  cache = FALSE)

# don't use dingbats in PDFs, in order to create Illustrator-friendly figures
grDevices::pdf.options(useDingbats = FALSE)

```

```{r read in config file}
config <- read_delim(file.path(params$assets,'projections.config.tsv'), delim = '\t', escape_double = FALSE, trim_ws = TRUE)
refs <- read_delim(file.path(params$assets,'references.tsv'), delim = '\t', escape_double = FALSE, trim_ws = TRUE)

# coerce to a list of param:value pairs, and make sure numeric parameters are numeric type
config <- as.list(tibble::deframe(config[, c(1, 2)]))
refs <- as.list(tibble::deframe(refs[,c(1,2)]))

# automatically convert each config element to the right type
config <- lapply(config, type.convert, as.is = TRUE)
refs <- lapply(refs, type.convert, as.is = TRUE)

config
refs
```

```{r create dirs}
# specify and create output and figures folders with run prefix
output_dir <- 'output'
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

figures_dir <- 'figures'
dir.create(figures_dir, showWarnings = TRUE, recursive = TRUE)

```

```{r read in query and ref data}

query <- readRDS(config$rds_dir)
DefaultAssay(query) <- "RNA"

query <- SetIdent(query, value = "tumor.plasmids.malignancy.25")
query_malignant <- subset(query, idents = "Tumor")

query_malignant <- query_malignant %>%
  FindVariableFeatures() %>%
  ScaleData(vars.to.regress = c("nCount_RNA","gender.score","percent.mt", "S.Score","G2M.Score"), 
            features = rownames(query_malignant)) %>%
  RunPCA()

Filbin <- readRDS(file = refs$`Filbin et al. 2017`)
Filbin$author <- "Filbin"
Filbin$tumor <- Filbin$celltypes

Liu <- readRDS(file = refs$`Liu et al. 2022`)
Liu$author <- "Liu"
Liu$celltypes <- Liu$annotation
Liu$tumor <- Liu$annotation

Gillen <- readRDS(file = refs$`Gillen et al. 2020`)
Gillen$author <- "Gillen"
Gillen$celltypes <- Gillen$cell_type
Gillen$tumor <- Gillen$tumor_subtype

ref <- merge(x = Filbin, y = c(Liu, Gillen),
             add.cell.ids = c("Filbin","Liu","Gillen"), 
             merge.data = F)

query_malignant
ref
```

```{r}

reference <- subset(ref, subset = tumor %in% c('AC-like', 'MES-like', 
                                                          'OC-like', 'OPC', 'OPC-like-1', 
                                                         'OPC-like-2', 'OPC-like-3',
                                                        'Cellline', 'Malignant',
                                                        'PDX', 'GBM','PFA1','PFA2'))
unique(reference$tumor)
```


```{r}
reference <- reference %>% NormalizeData() %>% 
                FindVariableFeatures()%>%ScaleData()%>%
                RunPCA()
```

```{r}
reference <- reference %>% 
    RunUMAP(reduction = "pca", dims = 1:10, return.model = TRUE) %>% 
    FindNeighbors(reduction = "pca", dims = 1:10) %>% 
    FindClusters(resolution = 0.5) %>% 
    identity()
```

```{r ref_dimplot, fig.height=5, fig.width=10}
dittoDimPlot(reference, 
             reduction.use = "umap", var = "author", 
             do.label = T, labels.size = 3, size = 0.5)

dittoSeq::dittoDimPlot(reference, 
             reduction.use = "umap", var = "tumor", 
             do.label = T, labels.size = 3, size = 1)
```

```{r}
reference$tumor <- recode(reference$tumor,
                              'AC-like' = 'DMG',
                              'MES-like' = 'DMG',
                              'OC-like' = 'DMG',
                              'OPC' = 'DMG',
                              'OPC-like-1' = 'DMG',
                              'OPC-like-2' = 'DMG',
                              'OPC-like-3' = 'DMG',
                              'Malignant' = 'DMG')
unique(reference$tumor)
```

```{r}
anchors <- FindTransferAnchors(
  reference = reference,
  query = query_malignant,
  normalization.method = "LogNormalize",
  reference.reduction = "pca",
  dims = 1:50
)

query_malignant <- TransferData(
  anchorset = anchors, 
  reference = reference,
  query = query_malignant,
  refdata = list(
      type = 'tumor'),
  prediction.assay = TRUE
)

query_malignant <- IntegrateEmbeddings(
  anchorset = anchors,
  reference = reference,
  query = query_malignant, 
  new.reduction.name = "ref.pca"
)

query_malignant <- ProjectUMAP(
  query = query_malignant, 
  query.reduction = "ref.pca", 
  reference = reference, 
  reference.reduction = "pca", 
  reduction.model = "umap"
)

check <- MappingScore(anchors = anchors, ndim = 50)
```

```{r dimplot, fig.height=5, fig.width=10}
dittoDimPlot(query_malignant, 
             reduction.use = "ref.umap", var = "predicted.type", 
             do.label = T, labels.size = 3, size = 0.5)

dittoDimPlot(query_malignant, 
             reduction.use = "umap", var = "predicted.type", 
             do.label = T, labels.size = 3, size = 0.5)
```

```{r comparison_heatmap, fig.height=5, fig.width=10}
query_malignant <- SetIdent(query_malignant, value = "predicted.id.Liu")

colors <- structure(c('#E69F00','#56B4E9', '#009E73', '#F0E442'),
                   names = names(table(query_malignant@active.ident)))
colors

reds <- brewer.pal(10, name = "Reds")

dittoHeatmap(query_malignant, 
             assay = "prediction.score.type")

DoHeatmap(query_malignant, 
          features = c('DMG','Cellline','PDX', 'GBM',"PFA1","PFA2"), 
          assay = 'prediction.score.type',
          group.colors = colors,
          angle = 90, size = 3,
          slot = 'data',
          raster = TRUE) +
  scale_fill_gradient(low = "#FFFFFF", high = "#CB181D") +
  ggtitle("Similarity comparison based on predicted.id.score")

do_ExpressionHeatmap(query_malignant, 
                     features = c('DMG','Cellline','PDX', 'GBM',"PFA1","PFA2"),
                     assay = "prediction.score.type",
                     flip = T,
                     features.order = rev(c('DMG','Cellline','PDX', 'GBM',"PFA1","PFA2"))) +
    scale_fill_gradient(low = "#FFFFFF", high = "#CB181D")
  

```
